export const SUPPORTED_LANGUAGES = [
  { lang: "af", region: "ZA", label: "Afrikaans (South Africa)" },
  { lang: "ar", region: "SA", label: "Arabic (Saudi Arabia)" },
  { lang: "ar", region: "EG", label: "Arabic (Egypt)" },
  { lang: "ar", region: "JO", label: "Arabic (Jordan)" },
  { lang: "ar", region: "KW", label: "Arabic (Kuwait)" },
  { lang: "ar", region: "LB", label: "Arabic (Lebanon)" },
  { lang: "ar", region: "MA", label: "Arabic (Morocco)" },
  { lang: "ar", region: "QA", label: "Arabic (Qatar)" },
  { lang: "ar", region: "AE", label: "Arabic (UAE)" },
  { lang: "ar", region: "TN", label: "Arabic (Tunisia)" },
  { lang: "ar", region: "OM", label: "Arabic (Oman)" },
  { lang: "bg", region: "BG", label: "Bulgarian (Bulgaria)" },
  { lang: "ca", region: "ES", label: "Catalan (Spain)" },
  { lang: "zh", region: "CN", label: "Chinese, Mandarin (Simplified, China)" },
  {
    lang: "zh",
    region: "TW",
    label: "Chinese, Mandarin (Traditional, Taiwan)",
  },
  {
    lang: "zh",
    region: "HK",
    label: "Chinese, Cantonese (Traditional, Hong Kong)",
  },
  { lang: "hr", region: "HR", label: "Croatian (Croatia)" },
  { lang: "cs", region: "CZ", label: "Czech (Czech Republic)" },
  { lang: "da", region: "DK", label: "Danish (Denmark)" },
  { lang: "nl", region: "NL", label: "Dutch (Netherlands)" },
  { lang: "en", region: "AU", label: "English (Australia)" },
  { lang: "en", region: "CA", label: "English (Canada)" },
  { lang: "en", region: "IN", label: "English (India)" },
  { lang: "en", region: "IE", label: "English (Ireland)" },
  { lang: "en", region: "NZ", label: "English (New Zealand)" },
  { lang: "en", region: "ZA", label: "English (South Africa)" },
  { lang: "en", region: "GB", label: "English (United Kingdom)" },
  { lang: "en", region: "US", label: "English (United States)" },
  { lang: "fi", region: "FI", label: "Finnish (Finland)" },
  { lang: "fr", region: "CA", label: "French (Canada)" },
  { lang: "fr", region: "FR", label: "French (France)" },
  { lang: "de", region: "DE", label: "German (Germany)" },
  { lang: "el", region: "GR", label: "Greek (Greece)" },
  { lang: "he", region: "IL", label: "Hebrew (Israel)" },
  { lang: "hi", region: "IN", label: "Hindi (India)" },
  { lang: "hu", region: "HU", label: "Hungarian (Hungary)" },
  { lang: "id", region: "ID", label: "Indonesian (Indonesia)" },
  { lang: "it", region: "IT", label: "Italian (Italy)" },
  { lang: "ja", region: "JP", label: "Japanese (Japan)" },
  { lang: "ko", region: "KR", label: "Korean (Korea)" },
  { lang: "ms", region: "MY", label: "Malay (Malaysia)" },
  { lang: "no", region: "NO", label: "Norwegian (Norway)" },
  { lang: "pl", region: "PL", label: "Polish (Poland)" },
  { lang: "pt", region: "BR", label: "Portuguese (Brazil)" },
  { lang: "pt", region: "PT", label: "Portuguese (Portugal)" },
  { lang: "ro", region: "RO", label: "Romanian (Romania)" },
  { lang: "ru", region: "RU", label: "Russian (Russia)" },
  { lang: "sr", region: "RS", label: "Serbian (Serbia)" },
  { lang: "sk", region: "SK", label: "Slovak (Slovakia)" },
  { lang: "es", region: "AR", label: "Spanish (Argentina)" },
  { lang: "es", region: "BO", label: "Spanish (Bolivia)" },
  { lang: "es", region: "CL", label: "Spanish (Chile)" },
  { lang: "es", region: "CO", label: "Spanish (Colombia)" },
  { lang: "es", region: "CR", label: "Spanish (Costa Rica)" },
  { lang: "es", region: "EC", label: "Spanish (Ecuador)" },
  { lang: "es", region: "SV", label: "Spanish (El Salvador)" },
  { lang: "es", region: "ES", label: "Spanish (Spain)" },
  { lang: "es", region: "US", label: "Spanish (United States)" },
  { lang: "es", region: "MX", label: "Spanish (Mexico)" },
  { lang: "es", region: "GT", label: "Spanish (Guatemala)" },
  { lang: "es", region: "HN", label: "Spanish (Honduras)" },
  { lang: "es", region: "NI", label: "Spanish (Nicaragua)" },
  { lang: "es", region: "PA", label: "Spanish (Panama)" },
  { lang: "es", region: "PY", label: "Spanish (Paraguay)" },
  { lang: "es", region: "PE", label: "Spanish (Peru)" },
  { lang: "es", region: "PR", label: "Spanish (Puerto Rico)" },
  { lang: "es", region: "DO", label: "Spanish (Dominican Republic)" },
  { lang: "es", region: "UY", label: "Spanish (Uruguay)" },
  { lang: "es", region: "VE", label: "Spanish (Venezuela)" },
  { lang: "sv", region: "SE", label: "Swedish (Sweden)" },
  { lang: "th", region: "TH", label: "Thai (Thailand)" },
  { lang: "tr", region: "TR", label: "Turkish (Turkey)" },
  { lang: "uk", region: "UA", label: "Ukrainian (Ukraine)" },
  { lang: "vi", region: "VN", label: "Vietnamese (Vietnam)" },
];

export const getUniqueLanguages = () =>
  Array.from(
    SUPPORTED_LANGUAGES.reduce(
      (acc, cur) => acc.add(cur.lang),
      new Set<string>()
    )
  );
